export const dummyNames = [
  "Alice Johnson",
  "Bob Smith",
  "Carol Williams",
  "David Brown",
  "Emily Jones",
  "Frank Garcia",
  "Grace Miller",
  "Henry Davis",
  "Isabella Rodriguez",
  "Jack Wilson",
  "Katherine Moore",
  "Liam Taylor",
  "Mia Anderson",
  "Noah Thomas",
  "Olivia Martin",
  "Patrick White",
  "Quinn Harris",
  "Ryan Clark",
  "Sophia Lewis",
  "Tyler Walker",

  "Erin Adams",
  "Felix Baker",
  "Gwendolyn Nelson",
  "Hugo Carter",
  "Ivy Mitchell",
  "Jasper Perez",
  "Kayla Roberts",
  "Leo Turner",
  "Maya Phillips",
  "Nathan Campbell",
];
